import { invoke } from "@tauri-apps/api/core";

// --- Enums (mirror the Rust models) ---

export type TaskStatus = "backlog" | "todo" | "in_progress" | "in_review" | "done";
export type TaskPriority = "low" | "high" | "urgent";
export type TaskLabel = "feat" | "fix" | "refactor" | "chore";
export type ProjectStatus = "active" | "cancelled" | "planned";

// --- Models ---

export interface Project {
  id: string;
  name: string;
  description: string | null;
  status: ProjectStatus;
  logoPath: string | null;
  url: string | null;
  githubUrl: string | null;
  githubStars: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewProject {
  name: string;
  description?: string | null;
  url?: string | null;
  githubUrl?: string | null;
  githubStars?: number | null;
}

// Universal patch: omit a field to leave it unchanged; pass `null` to clear a
// nullable column. `id`/`createdAt` are immutable.
export interface UpdateProject {
  name?: string;
  description?: string | null;
  status?: ProjectStatus;
  logoPath?: string | null;
  url?: string | null;
  githubUrl?: string | null;
  githubStars?: number | null;
}

export interface Task {
  id: string;
  taskId: string;
  projectId: string;
  title: string;
  description: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  label: TaskLabel | null;
  githubBranch: string | null;
  position: number;
  plannedFor: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface NewTask {
  projectId: string;
  title: string;
  description?: string | null;
  priority?: TaskPriority;
  label?: TaskLabel;
  plannedFor?: string | null;
}

// Universal patch: omit a field to leave it unchanged; pass `null` to clear a
// nullable column. `id`/`taskId`/`createdAt` are immutable.
export interface UpdateTask {
  projectId?: string;
  title?: string;
  description?: string | null;
  status?: TaskStatus;
  priority?: TaskPriority;
  label?: TaskLabel | null;
  githubBranch?: string | null;
  position?: number;
  plannedFor?: string | null;
}

// --- API: errors reject as { kind, message } from the Rust AppError ---

export const projects = {
  create: (input: NewProject) => invoke<Project>("create_project", { input }),
  list: () => invoke<Project[]>("list_projects"),
  update: (id: string, patch: UpdateProject) => invoke<Project>("update_project", { id, patch }),
  remove: (id: string) => invoke<void>("remove_project", { id }),
};

export const tasks = {
  // `taskId` and `githubBranch` are generated by the backend.
  create: (input: NewTask) => invoke<Task>("create_task", { input }),
  list: (projectId: string) => invoke<Task[]>("list_tasks", { projectId }),
  update: (id: string, patch: UpdateTask) => invoke<Task>("update_task", { id, patch }),
  remove: (id: string) => invoke<void>("remove_task", { id }),
};
